### ISSUE TITLE
Detectar movimentação estranha do usuário durante o trajeto para agir em caso de perigo

### ISSUE THREAD

**Issue by matheuslc** [dieacetaria/margaret#4]
# O quê?
Temos que detectar antes uma movimentação estranha do usuário durante o percurso que ela marcou para ser acompanhada. Se conseguirmos antecipar um perigo sem que o usuário tome uma ação é melhor porque a vítima pode ter dificuldade de usar o celular

# Problemas ainda não respondidos
* Como agiremos? Comunicação direta para quem está acompanhando?
* Em alguma momento comunicaremos a polícia?

**Comment by matheuslc** [comment]
Usuário obrigatoriamente precisa dizer qual o destino final do seu trajeto.
Iremos monitorar o trajeto da pessoas e alguns pontos, como:
- Se ela saiu do trajeto
- Se ela ficou parada algum tempo
- Se ficou muito tempo sem responder (o aplicativo enviando dados, perdeu a conexão)

**Comment by heitormurara** [comment]
**Todo's:**

- [ ] Verificar possibilidade de compartilhar localização em background: @dieacetaria/android
- [x] Verificar possibilidade de compartilhar localização em background: @dieacetaria/ios 
- [x] Verificar SDK de mapas existentes: @dieacetaria/backend

**Comment by heitormurara** [comment]
SDK de mapas existentes: https://docs.google.com/spreadsheets/d/1HE5aKuSSJEesnFftXu82SRW2F0rRlQziM80qSlPMriQ/

**Comment by heitormurara** [comment]
iOS: https://github.com/malcommac/SwiftLocation
